---
name: build
env:
  MIX_ENV: test
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup elixir
        uses: actions/setup-elixir@v1.0.0
        with:
          elixir-version: 1.9.x
          otp-version: 22.x

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Get deps cache
        uses: actions/cache@v1
        with:
         path: deps/
         key: ${{ runner.os }}-deps-${{ hashFiles('**/mix.lock') }}
         restore-keys: ${{ runner.os }}-deps-

      - name: Get build cache
        uses: actions/cache@v1 
        with:
          path: _build/test/
          key: ${{ runner.os }}-build-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-build-

      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix compile

      - name: Run Tests
        run: |
          mix coveralls.github
